flask_openapi3/models/path.py, flask_openapi3/openapi.py
Exposed support for path operation field `deprecated` as specified in [oas 3.0.3 fixed fields](https://spec.openapis.org/oas/v3.0.3#fixed-fields-7)
* add support for both APIBlueprint and OpenAPI classes 
*  modified _do_decorator and each REST verb
=> exposed support for path operation field `deprecated`

flask_openapi3/openapi.py
Allow customising the URL used to serve the openapi json and UI.
Tested with
```
app = OpenAPI(
__name__,
info="Book API",
doc_prefix="v1/book/openapi",
)
```
Thank you!
=> Add parameter to customise the doc_ui URL path

examples/response_demo.py, flask_openapi3/api_blueprint.py, flask_openapi3/openapi.py, flask_openapi3/types.py, flask_openapi3/utils.py, tests/test_restapi.py
- Added support for [Empty Response Body](https://swagger.io/docs/specification/describing-responses/#empty)
- Created unittest for Empty Response Body
- Changed the `OpenAPIResponsesType` to allow the value of the dictionary to be `None`
- Added example for Empty Response Body
Checklist:
=> Add support for "empty response body" (HTTP status code 204)

flask_openapi3/utils.py, tests/test_restapi.py
I run into a bug when writing unittests there validated the returned JSON-object which contains a `list`.
I created 2 unittests to verify that my bug fix works :D
Checklist:
=> Response List: Fixed bug - The code for validation responses can now handle `list`

flask_openapi3/models/common.py, flask_openapi3/models/path.py, flask_openapi3/models/server.py, flask_openapi3/utils.py, tests/test_openapi.py
Checklist:
Note that I had to move Response model class to another file due to dependencies on sub models. EVen if it's public, I expect it to be without impact as it is not documented, so it should not be used.
fixes #35
=> extra_responses allow to provide description, links, headers and (additional) content

docs/Quickstart.md
Checklist:
This PR fixed the link to the complete example of Class-based API View. The link I provided may not be the best, but it is definitely better than the existing one. Additionally, I also provided some rewording.
=> Correct link

docs/Tutorial/Specification.md
Checklist:
I have provided a more clear explanation of the usage of the `flask openapi` command in this PR. This PR should close #63.
=> Explain usage of `flask openapi` command more clearly

flask_openapi3/api_blueprint.py, flask_openapi3/openapi.py, tests/test_api_blueprint.py, tests/test_restapi.py
=> feat: Add operation_id_callback to v1.x

flask_openapi3/__init__.py, flask_openapi3/openapi.py, flask_openapi3/scaffold.py, flask_openapi3/view.py, tests/test_api_view_args.py
Checklist:
This is a wip, should close https://github.com/luolingchun/flask-openapi3/issues/66
I'll come back to the checklist shortly, i'm open to discussion on whether this is remotely the correct way to approach this problem!
~~I noticed that the view_class was never actually instantiated, if you inherit from `flask.views.MethodView` you can call `as_view` which deals with the class view instantiation automatically.~~
I stole this mostly from:
https://github.com/flask-restful/flask-restful/blob/b52b18807d2bbde0075bfc4f851161c1454c5368/flask_restful/__init__.py#L437
~~flasks `as_view`:
https://github.com/pallets/flask/blob/9659b11a45281662c6aa1194dc95b46b1f566ba6/src/flask/views.py#L85~~
basic usage:
```
@api_view.route("/test")
class List:
def __init__(self, test=None):
print("init …
```
=> Init view_class and pass kw/args

docs/Usage/Model_Config.md, flask_openapi3/utils.py, tests/test_model_config.py
Checklist:
```python
class BookQuery(BaseModel):
age: int
author: str
metadata: Dict[str, str] = Field(alias='metadata_')
class Config:
by_alias = False
```
With `by_alias = False`:
Without:
=> [#79] Support `by_alias` in Model Config

flask_openapi3/utils.py, tests/test_openapi.py, tests/test_utils.py
Checklist:
When we use generics in responses, the schema name include `[]` but [OpenAPI 3 doesn't allow it](https://spec.openapis.org/oas/v3.1.0#components-object).
```
All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.
```
The pydantic normalize all `$ref` but the schema name ( `components.schemas` ) set by this library so we shuld normalize name using pydantic's function.
=> bugfix for gneerics class

flask_openapi3/utils.py, tests/test_openapi.py
Checklist:
The parameter object include all files in schema object by this code.
https://github.com/luolingchun/flask-openapi3/blob/master/flask_openapi3/utils.py#L181
But parameter object doesn't allow all fields, for example `title` `type` ( you can get these error for previous commit 24999e44ebfb7d1d06bbaad72bdcdc05bfbb0a34 )
````
E           AssertionError: assert {'deprecated'...: 'path', ...} == {'deprecated'...: 'path', ...}
E             Omitting 7 identical items, use -vv to show
E             Left contains 3 more items:
E             {'maxLength': 300, 'title': 'Type Name', 'type': 'string'}
E             Use -v to get more diff
E           AssertionError: assert {'deprecated'... 'query', ...} == {'deprecated'... 'query', ...}
E             Omitting 7 identical items, use -vv to …
```
=> bugfix for parameter object

docs/Usage/Request.md, examples/raw_request_demo.py, flask_openapi3/__init__.py, flask_openapi3/blueprint.py, flask_openapi3/models/__init__.py, flask_openapi3/openapi.py, flask_openapi3/request.py, flask_openapi3/scaffold.py, flask_openapi3/types.py, flask_openapi3/utils.py, flask_openapi3/view.py, tests/test_request.py
Checklist:
Regarding the idea of supporting raw requests, there is no data validation and support for OpenAPI UI.
```python
from flask_openapi3 import OpenAPI
from flask_openapi3 import RawModel
app = OpenAPI(__name__)
class BookRaw(RawModel):
mimetypes = ["text/csv", "application/json"]
@app.post("/book")
def get_book(raw: BookRaw):
print(raw.data)
print(raw.mimetype)
return "ok"
if __name__ == "__main__":
app.run(debug=True)
```
=> support for raw requests

flask_openapi3/blueprint.py, tests/test_api_blueprint.py, tests/test_options_in_viewfunc.py
=> Fix the same operationId

docs/Usage/Model_Config.md, flask_openapi3/utils.py
=> [#125] Enable to mark the RequestBody as Optional.

flask_openapi3/request.py, tests/test_form.py
* The default value defined in the form is invalid
fix #126
fix #128 
Checklist:
=> The default value defined in the form is invalid (#128 )

flask_openapi3/utils.py, tests/test_pydantic_calculated_fields.py
Fixed issue with pydantic computed fields not appearing in openapi.json.
Checklist:
fix #139
=> Fix mssing Pydantic Calculated Fields

docs/Usage/Specification.md, flask_openapi3/openapi.py, flask_openapi3/templates/__init__.py, tests/test_swagger_config.py
=> Add the `swagger_config` parameter to configure the swagger ui

flask_openapi3/models/schema.py, tests/test_number_constraints.py
This fixes #150 
In `Schema` class `exclusiveMinimum` and `exclusiveMaximum` fields should be of type `float` instead of `bool`.
If you try to use the Pydantic `Field()` with the 'gt' or 'lt' constraint, the app crashes.
Checklist:
=> Wrong types of exclusiveMinimum & exclusiveMaximum fields in Schema class

flask_openapi3/blueprint.py, flask_openapi3/openapi.py, flask_openapi3/utils.py, flask_openapi3/view.py, tests/test_openapi.py
=> Fix missing `Field.default` when it's value is `None` in openapi spec

flask_openapi3/models/server_variable.py, tests/test_server.py
=> ServerVariable.enum should be optional

flask_openapi3/models/schema.py, tests/test_openapi.py
=> Add PrefixItems to Schema Model for use with Tuple types

flask_openapi3/request.py, tests/test_model_extra.py
=> Fix query, form, header model extra not honored

flask_openapi3/openapi.py
This will make it easier for APISpec to be modified by external functions before generating the spec_json (examples: adding webhooks, registering custom components etc).
Checklist:
close #190
=> Better APISpec init to allow to modify it before generating `spec_json`.

flask_openapi3/models/schema.py, tests/test_openapi.py
=> Schema.maximum type `float` -> `int | float`

.github/workflows/tests.yml, flask_openapi3/openapi.py, flask_openapi3/view.py, tests/test_url_prefix.py
=> Allow url_prefix to be set during API/APIView registration

flask_openapi3/models/media_type.py, flask_openapi3/models/parameter.py, flask_openapi3/models/path_item.py, flask_openapi3/models/reference.py, flask_openapi3/models/schema.py, flask_openapi3/models/security_scheme.py
This PR adds `"populate_by_name": True` to the `model_config` for the `SecurityScheme` model
When creating the application, we can define supported security schemes using plain dicts or the `SecurityScheme` object. The `SecurityScheme` object is more typesafe but must eventually be dumped to JSON in order for the API docs to be generated.
```
app = OpenAPI(
"app",
security_schemes={
"jwt": {"type": "http", "scheme": "bearer"},
"key": {"type": "apiKey", "in": "header", "name": "X-APP-API-KEY"},
},
)
```
OR
```
app = OpenAPI(
"app",
security_schemes={
"jwt": SecurityScheme(type="http", scheme="bearer"},
"key": SecurityScheme(type="apiKey", security_scheme_in="header", name="X-APP-API-KEY"),
},
)
```
The [`in`](https://spec.openapis.org/oas/v3.1.0#security-scheme-object) keyword is reserved …
=> fix(models): enable 'populate_by_name' to alias fields correctly

CONTRIBUTING.md, flask_openapi3/openapi.py, tests/test_api_blueprint.py, tests/test_api_view.py
In a situation where we may instantiate multiple apps that register the same blueprint, this change updates register_api to always update the APIBlueprint's instance variables to the same values no matter how many times it is invoked.
Checklist:
For the fix here, I opted to update an additional field in the api rather than not updating the API because I thought that it would be helpful to have the proper updated `api.paths` field. I'm open to other approaches as well!
=> Fixes issue where register_api isn't idempotent

docs/Usage/Request.md, flask_openapi3/request.py, tests/test_validate_request.py
Checklist:
@luolingchun The test in `tests/test_validate_request.py` illustrates the problem.
Our auth decorator injects some kwargs into the function which now get dropped.
My change makes any kwargs used by the path model be omitted, but other kwargs are kept.
=> Make validate_request pass on existing kwargs but remove those part of path

flask_openapi3/models/validation_error.py, tests/test_pydantic_v2_validation_error.py, tests/test_pydantic_validation_error.py
Fixes #231 
The ValidationError schema in OpenAPI documentation doesn't match the actual Pydantic v2 validation error responses, causing confusion for API consumers.
**OpenAPI Schema:**
```json
{
"ctx": null,
"loc": null, 
"msg": null,
"type_": null
}
```
**Actual Response:**
```json
{
"type": "missing",
"loc": ["email"],
"msg": "Field required", 
"input": {"invalid_field": "test"},
"url": "https://errors.pydantic.dev/2.11/v/missing"
}
```
Both OpenAPI schema AND actual responses now use the same Pydantic v2 format! ✅
Updated `ValidationErrorModel` in `flask_openapi3/models/validation_error.py` to align with Pydantic v2 error format:
- **Changed `type_` → `type`** (correct Pydantic v2 field name)
- **Added `input` field** (required in Pydantic v2)  
- **Added `url` field** (present in …
=> Fix ValidationError schema to match Pydantic v2 format
