luolingchun/flask-openapi3

examples/pydantic_custom_root_types.py
flask_openapi3/openapi.py
flask_openapi3/utils.py
tests/test_pydantic_custom_root_types.py

give a look in this fix to enable __root__ feature of pydantic.
```
class SelloutList(BaseModel):
__root__: List[Sellout]
@app.post('/api/v1/sellouts',
tags=[Tag(name='Sellout', description='Loren.')],
responses={'200': SelloutList}
)
def post_sellout(body: SelloutList):
```

Fix to enable BaseModel with __root__ property.

---

.github/workflows/test.yml
CHANGELOG.md
docs/OpenAPI/Specification.md
docs/Quickstart.md
docs/Quickstart.zh.md
examples/nested_apiblueprint_demo.py
examples/response_demo.py
flask_openapi3/__version__.py
flask_openapi3/api_blueprint.py
flask_openapi3/commands.py
flask_openapi3/markdown.py
flask_openapi3/models/common.py
flask_openapi3/openapi.py
flask_openapi3/types.py
flask_openapi3/utils.py
requirements-dev.txt
requirements.txt
setup.py
tests/test_fixed_externaldocs_support.py
tests/test_nested_apiblueprint.py
tests/test_options_in_viewfunc.py
tests/test_restapi.py
tests/test_restapi_with_doc_prefix.py

Working for 2.x

---

docs/OpenAPI/Request.md
flask_openapi3/api_blueprint.py
flask_openapi3/models/common.py
flask_openapi3/openapi.py
flask_openapi3/utils.py
tests/test_openapi.py

Allow to provide body_examples

---

requirements.txt

Checklist:
fixes #34 
Can you release a new version on this is merged? Thanks again

Pin pydantic to version 1

---

README.md
docs/Quickstart.md
docs/Quickstart.zh.md
docs/Reference/APIView.md
docs/index.zh.md
examples/api_view_demo.py
flask_openapi3/__init__.py
flask_openapi3/api_blueprint.py
flask_openapi3/api_view.py
flask_openapi3/do_wrapper.py
flask_openapi3/openapi.py
flask_openapi3/scaffold.py
flask_openapi3/view.py
mkdocs.yml
tests/test_api_view.py

Support APIView

---

flask_openapi3/blueprint.py
flask_openapi3/utils.py
flask_openapi3/view.py
tests/test_api_view.py
tests/test_nested_apiblueprint.py

[#82] Fix parameter in url_prefix

---

flask_openapi3/models/encoding.py
flask_openapi3/request.py
flask_openapi3/utils.py
tests/test_form.py

Added ability to deserialize complex form parameter objects

---

flask_openapi3/utils.py
tests/test_response.py

[#97] Fix response miss description

---

flask_openapi3/utils.py
tests/test_openapi.py

Fix cookie extra properties

---

.github/workflows/tests.yml
CONTRIBUTING.md
flask_openapi3/blueprint.py
flask_openapi3/openapi.py
flask_openapi3/scaffold.py
pyproject.toml
requirements/doc.txt
requirements/requirements.txt

Support Flask 3.0

---

flask_openapi3/blueprint.py
flask_openapi3/openapi.py
flask_openapi3/request.py
flask_openapi3/scaffold.py

Checklist:
---
- `_do_decorator -> _collect_openapi_info`
- `_do_header -> _validate_header`
- `_do_cookie -> _validate_cookie`
-  `_do_path -> _validate_path`
-  `_do_query -> _validate_query`
-  `_do_form -> _validate_form`
- `_do_body -> _validate_body`
- `_do_request -> _validate_request`

Use understandable function names

---

.github/workflows/tests.yml
CONTRIBUTING.md
pyproject.toml

Update pydantic to 2.4

---

.github/workflows/docs.yml
.github/workflows/tests.yml
flask_openapi3/openapi.py
tests/test_validation_error.py

Fix missed components schemas in ValidationErrorModel

---

flask_openapi3/openapi.py
tests/test_response.py

Skip 422 response non parameters

---

docs/Usage/Configuration.md
docs/Usage/Specification.md
docs/Usage/UI_Templates.md
flask_openapi3/openapi.py
mkdocs.yml
tests/test_validation_error.py

Support SWAGGER_CONFIG and OAUTH_CONFIG in app.config

---

flask_openapi3/request.py

Fix empty list in body

---

flask_openapi3/request.py

Fix `populate_by_name` when execute `model_validate`

---

flask_openapi3/models/file.py

Fix __get_pydantic_core_schema__

---

flask_openapi3/request.py
tests/test_list_with_default_value.py
tests/test_request.py

Fix list with default value

---

flask_openapi3/request.py
tests/test_populate_by_name.py

Checklist:
fix: #182
fix: #183

Fix alias in query and form

---

flask_openapi3/utils.py

Reuse schema["title"] if it's defined

---

flask_openapi3/models/__init__.py

Simple webhook schema

---

docs/Usage/Route_Operation.md
flask_openapi3/blueprint.py
flask_openapi3/utils.py
tests/test_api_blueprint.py
tests/test_options_in_viewfunc.py

Checklist:
fix: #222 
@jangxx I submitted a PR and I hope you have time to test it.

operation_id_callback with blueprint name and func name
